version: '3'
services:
  api:
    image: bitnami/postgresql:17.0.0
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=username
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=postgres
